version: "3.8"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html
    container_name: php_app
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - /home/fgarcia/repositories/docker-alpine/app:/var/www/html
    container_name: apache_app
    environment:
      - PROJECT_PATH_VH=${PROJECT_PATH}
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/fgarcia/repositories/docker-alpine/comunidadlegal_stg.sql:/docker-entrypoint-initdb.d/comunidadlegal_stg.sql
      - /home/fgarcia/repositories/docker-alpine/data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_app
networks:
  frontend:
  backend:
volumes:
  data: