version: "3.2"
services:
  php:
    build:
      context: './php/'
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html/
    container_name: php_shopify
networks:
  frontend:
  backend:
