version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    ports:
      - "6001:6001"
    volumes:
      - ${PROJECT_ROOT}/:/app/
    container_name: php_shopify
  nginx:
    build:
      context: './nginx/'
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ${PROJECT_ROOT}/:/app/
    container_name: nginx_shopify
networks:
  frontend:
  backend:
volumes:
  data:
