version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    ports:
      - "6001:6001"
    volumes:
      - ${PROJECT_ROOT}/:/app/
    container_name: php_shopify
networks:
  frontend:
  backend:
volumes:
  data:
