version: "3.8"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    container_name: php_app
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - ${PUERTO_WEB}
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    container_name: apache_app
    environment:
      - PROJECT_SERVER_NAME=${PROJECT_SERVER_NAME}
      - PROJECT_SERVER_ALIAS=${PROJECT_SERVER_ALIAS}
      - PROJECT_NAME=${PROJECT_NAME}
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - ${PUERTO_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_app
  mailhog:
    image: mailhog/mailhog
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
    ports: 
      - 1025:1025
      - 8025:8025
    networks:
      - backend
      - frontend
    container_name: mailhog_app
networks:
  frontend:
  backend:
volumes:
  mysql_data: